### ISSUE TITLE
Can you help me how to use your api ?

### ISSUE THREAD

**Issue by thanhtutoo** [rohmanhm/simple-blog-crud-laravel#1]
Since, I am noob in api region, could you guide me how to use your api effectively, I tried with postman , by going http://localhost:8000/api/login , with post method, [http://imgur.com/a/zmbNV](url)

Please guide me, thank you.

**Comment by rohmanhm** [comment]
You can't use Postman.
as you can see `Line 73`
> TokenMissmatchException

Because Laravel uses CSRF Token to validate where data coming from.

**Comment by thanhtutoo** [comment]
So , how can i use your api url effectively, by just typing  http://localhost:8000/api/login 
 http://localhost:8000/api/register, 
Thanks for your fast response :)

**Comment by rohmanhm** [comment]
Disable Laravel CSRF Middleware.
I hope this post will help you. 

- https://laravel.io/forum/11-14-2014-disabling-the-csrf-middleware-in-laravel-5
- https://laracasts.com/discuss/channels/general-discussion/l5-disable-csrf-middleware-on-certain-routes
